// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/logs": {
            "post": {
                "description": "创建一条新的聊天日志记录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "创建聊天日志",
                "parameters": [
                    {
                        "description": "日志信息",
                        "name": "request",
                        "in": "body",
                        "required": 不涉密,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateLogRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LogResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.LogResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.LogResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateLogRequest": {
            "description": "创建日志的请求参数",
            "type": "object",
            "required": [
                "text"
            ],
            "properties": {
                "text": {
                    "description": "聊天文本内容",
                    "type": "string",
                    "example": "这是一条聊天记录"
                },
                "validation_result": {
                    "description": "验证结果",
                    "type": "string",
                    "example": "不涉密"
                }
            }
        },
        "handlers.LogResponse": {
            "description": "日志操作的响应结果",
            "type": "object",
            "properties": {
                "code": {
                    "description": "操作状态码",
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "description": "日志数据"
                },
                "message": {
                    "description": "操作消息",
                    "type": "string",
                    "example": "成功"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "10.238.165.208:8090",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Chat Log API",
	Description:      "记录聊天信息的API服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
