basePath: /api/v1
definitions:
  handlers.CreateLogRequest:
    description: 创建日志的请求参数
    properties:
      text:
        description: 聊天文本内容
        example: 这是一条聊天记录
        type: string
      validation_result:
        description: 验证结果
        example: true
        type: boolean
    required:
    - text
    type: object
  handlers.LogResponse:
    description: 日志操作的响应结果
    properties:
      code:
        description: 操作状态码
        example: 200
        type: integer
      data:
        description: 日志数据
      message:
        description: 操作消息
        example: 成功
        type: string
    type: object
host: localhost:8090
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://www.example.com/support
  description: 记录聊天信息的API服务
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Chat Log API
  version: "1.0"
paths:
  /logs:
    get:
      consumes:
      - application/json
      description: 获取指定日期范围内的聊天日志
      parameters:
      - description: 开始日期 (YYYY-MM-DD)
        in: query
        name: start_date
        type: string
      - description: 结束日期 (YYYY-MM-DD)
        in: query
        name: end_date
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LogResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.LogResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.LogResponse'
      summary: 获取聊天日志
      tags:
      - logs
    post:
      consumes:
      - application/json
      description: 创建一条新的聊天日志记录
      parameters:
      - description: 日志信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateLogRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LogResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.LogResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.LogResponse'
      summary: 创建聊天日志
      tags:
      - logs
swagger: "2.0"
